version: '3.6'
services:
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: unless-stopped
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=grafana
      - INFLUXDB_PASSWORD=grafana12345
    ports:
      - '8086:8086'
    volumes:
      - ./volumes/influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
      - ./volumes/grafana/conf/:/etc/grafana/

volumes:
  grafana_data: {}
  influxdb_data: {}
